version: '3.8'

services:
  backend:
    build:
      context: .
    image: merinmathew19/hosthunt:latest
    command: daphne project.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
