# Generated by Django 5.1.1 on 2024-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_method',
            field=models.CharField(choices=[('notification', 'Notification Only'), ('rentThroughHostHunt', 'Rent Through HostHunt')], default='notification', max_length=20),
        ),
    ]
