# Generated by Django 5.1.1 on 2024-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_rent_payment_method_rent_rent_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
    ]
