# Generated by Django 5.1.1 on 2024-12-18 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_rent_rent_method'),
        ('property', '0029_alter_rooms_room_thumbnail_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.FloatField(default=0, help_text='Rating for cleanliness (0-5)')),
                ('accuracy', models.FloatField(default=0, help_text='Rating for accuracy (0-5)')),
                ('check_in', models.FloatField(default=0, help_text='Rating for check-in experience (0-5)')),
                ('communication', models.FloatField(default=0, help_text='Rating for communication (0-5)')),
                ('location', models.FloatField(default=0, help_text='Rating for location (0-5)')),
                ('value', models.FloatField(default=0, help_text='Rating for value (0-5)')),
                ('overall_rating', models.FloatField(default=0, help_text='Overall rating (calculated)')),
                ('review_text', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.bookings')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_reviews', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True, help_text='True if the user liked the review')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='booking.bookingreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
