# Generated by Django 5.1.1 on 2024-12-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_bookings_new_id_alter_bookings_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='id',
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_id',
            field=models.CharField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
