# Generated by Django 5.1.1 on 2024-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rename_rent_id_rent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
