# Generated by Django 5.1.1 on 2025-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rent_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreview',
            name='review_replay',
            field=models.TextField(blank=True, help_text='Optional review replay by host', null=True),
        ),
    ]
