# Generated by Django 5.1.1 on 2025-01-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_bookingreview_review_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreview',
            name='review_replay_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for review replay last updated', null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='month_of_rent',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True),
        ),
    ]
