# Generated by Django 5.1.1 on 2024-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customowner_groups_customowner_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customowner',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
