# Generated by Django 5.1.1 on 2024-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customowner_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customowner',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customowner',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
