# Generated by Django 5.1.1 on 2025-01-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_userprofile_identity_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active_user',
            new_name='is_active',
        ),
    ]
