# Generated by Django 5.1.1 on 2025-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_identityverification_identity_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
