# Generated by Django 5.1.1 on 2024-10-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_remove_customowner_is_staff_customowner_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_type', models.CharField(blank=True, choices=[('gen', 'GENERAL')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('pg', 'PG'), ('rental', 'Rental'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='hostel_thumbnails/')),
                ('total_bed_rooms', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='in_progress', max_length=20)),
                ('is_listed', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('smoking', models.CharField(choices=[('yes_everywhere', 'Yes, Everywhere'), ('yes_designated', 'Yes, Designated Areas'), ('no', 'No')], default='no', max_length=20)),
                ('pets_permit', models.BooleanField(default=False)),
                ('drinking_permit', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('no_restriction', 'No Gender Restriction'), ('boys_only', 'Boys Only'), ('girls_only', 'Girls Only')], default='no_restriction', max_length=20)),
                ('visitors', models.BooleanField(default=True)),
                ('guardian', models.BooleanField(default=False)),
                ('child_permit', models.BooleanField(default=False)),
                ('child_from_age', models.DateTimeField(blank=True, null=True)),
                ('child_to_age', models.DateTimeField(blank=True, null=True)),
                ('curfew', models.BooleanField(default=False)),
                ('curfew_from_time', models.DateTimeField(blank=True, null=True)),
                ('curfew_to_time', models.DateTimeField(blank=True, null=True)),
                ('min_nights', models.IntegerField(blank=True, null=True)),
                ('max_nights', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.IntegerField()),
                ('free_cancellation', models.BooleanField(default=False)),
                ('cancellation_period', models.IntegerField(default=0)),
                ('caution_deposit', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='authentication.customowner')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField(default=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='property.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='property_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.property')),
            ],
        ),
    ]
