# Generated by Django 5.1.1 on 2024-10-07 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydocument',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='property',
            name='notice_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_thumbnails/'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('host', 'property_name', 'address', 'property_type')},
        ),
    ]
