# Generated by Django 5.1.1 on 2024-10-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertydocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyamenity',
            name='amenity',
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='property',
            name='host',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertydocument',
            name='property',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='PropertyAmenity',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyDocument',
        ),
    ]
