# Generated by Django 5.1.1 on 2024-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('ready_to_list', 'Ready to List')], default='in_progress', max_length=20),
        ),
    ]
