# Generated by Django 5.1.1 on 2024-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('ready_to_list', 'Ready to List'), ('published', 'Published')], default='in_progress', max_length=20),
        ),
    ]
