# Generated by Django 5.1.1 on 2024-10-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property',
            new_name='property_id',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image_url', models.URLField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentalApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildup_area', models.IntegerField()),
                ('property_age', models.IntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateTimeField()),
                ('floor_num', models.IntegerField()),
                ('rooms', models.CharField(max_length=255)),
                ('water_supply', models.BooleanField(default=False)),
                ('gas_pipeline', models.BooleanField(default=False)),
                ('furnishing_status', models.CharField(choices=[('fully', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=20)),
                ('furnishings', models.CharField(max_length=255)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_details_of_house', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=100)),
                ('is_private', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('occupancy', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('booking_amount_choice', models.CharField(choices=[('price_per_night', 'Price per night'), ('monthly_rent', 'Monthly Rent')], max_length=20)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bed_type', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('room_thumbnail_image_url', models.URLField(max_length=255)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image_url', models.URLField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='property.rooms')),
            ],
        ),
    ]
