# Generated by Django 5.1.1 on 2024-10-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_property_id_propertydocument_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyamenity',
            old_name='amenity',
            new_name='amenity_id',
        ),
        migrations.RenameField(
            model_name='propertyamenity',
            old_name='property',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='property',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='property',
            new_name='property_id',
        ),
    ]
