# Generated by Django 5.1.1 on 2024-10-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_rename_amenity_propertyamenity_amenity_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyamenity',
            old_name='amenity_id',
            new_name='amenity',
        ),
        migrations.RenameField(
            model_name='propertyamenity',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='property_id',
            new_name='property',
        ),
    ]
