# Generated by Django 5.1.1 on 2024-10-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_amenity_id_propertyamenity_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_thumbnail_image_url',
        ),
    ]
