# Generated by Django 5.1.1 on 2024-10-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_remove_rooms_room_thumbnail_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='doc_name',
            field=models.CharField(default='doc', max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='more_details_of_house', to='property.property'),
        ),
    ]
