# Generated by Django 5.1.1 on 2024-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_propertydocument_doc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('general', 'GENERAL'), ('entertainment', 'ENTERTAINMENT'), ('service', 'SERVICE')], max_length=100, null=True),
        ),
    ]
