# Generated by Django 5.1.1 on 2024-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_roomfacility_alter_amenity_amenity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gender_restriction',
            field=models.CharField(choices=[('no_restriction', 'No Gender Restriction'), ('male_only', 'Male Only'), ('female_only', 'Female Only')], default='no_restriction', max_length=20),
        ),
    ]
