# Generated by Django 5.1.1 on 2024-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_rooms_facilities_alter_rooms_bed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='jjj', max_length=255),
        ),
    ]
