# Generated by Django 5.1.1 on 2024-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_property_lat_alter_property_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_thumbnail_image_url',
            field=models.URLField(default='lkdfls', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
