# Generated by Django 5.1.1 on 2024-11-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_rooms_room_thumbnail_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomFacility',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
