# Generated by Django 5.1.1 on 2024-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_delete_roomfacility_alter_rooms_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='rooms',
            unique_together={('room_name', 'property')},
        ),
    ]
