# Generated by Django 5.1.1 on 2024-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_rooms_unique_together_rooms_availablility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='host',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='property',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='availablility',
        ),
        migrations.AddField(
            model_name='rooms',
            name='available_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookingPayment',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
