# Generated by Django 5.1.1 on 2024-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_remove_bookings_host_remove_bookings_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='occupancy',
            new_name='no_of_beds',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
