# Generated by Django 5.1.1 on 2024-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_rooms_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
